# Model Config
 
# Data Configs
data:
  dataroot: ./data/sample/images/
  labelroot: 
    train: ./data/sample/label/train.csv
    val: ./data/sample/label/test.csv
    test: ./data/sample/label/test.csv
  img_size: [32, 32]
  n_channels: 3
  classes: ['airplane', 'bird', 'car', 'cat', 'deer', 'dog', 'horse', 'monkey', 'ship', 'truck']
  color_mean: [0.4914, 0.4822, 0.4465]
  color_std: [0.2023, 0.1994, 0.2010]

# Training Configs
train:
  batch_size: 128
  epochs: 30
  optimizer:
    type: sgd
    lr: 0.001
    momentum: 0.9
    decay: 0.0001
  criterion:
    type: cross_entropy
  n_gpus: 1
  metrics: ['accuracy', 'precision', 'recall', 'f1score']
  save_ckpt_interval: 10
  resume:
    # e.g) resume: ./logs/2020-07-26T00:19:34.918002/ckpt/best_acc_ckpt.pth if resume. Blank if not resume

# Model Configs
model:
  name: resnet18
  n_classes: 10
  pretrained: False

# Other Configs
util:
  logdir: ./logs/

